[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install && cd server && npm install && cd ../client && npm install"]

[phases.build]
cmds = ["cd client && npm run build && cd ../server && npm run build"]

[start]
cmd = "cd server && npx tsx src/scripts/migrate.ts && node dist/index.js"
